---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: "retailops_1204"
    box_url: "https://media-retailme.apple.com/system/data/vagrant/retailops_1204_virtualbox.box"

suites:
- name: default
  run_list: ["recipe[cd-tools]"]
  attributes: {}

